### ISSUE TITLE
Fix non-power-of-two split()

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#1018]
Valid input:
```
staff = abjad.Staff()
staff.append(abjad.Container("c'4"))
halves = staff[0]._split_by_duration(
    abjad.Duration(1, 20),
    )
```
Should not error:
```
Traceback (most recent call last):
  File "/Users/trevorbaca/.abjad/abjad_tmp.py", line 11, in <module>
    abjad.Duration(1, 20),
  File "/Users/trevorbaca/abjad/abjad/core/Container.py", line 1150, in _split_by_duration
    raise ValueError(message)
ValueError: should not be able to get here.
```

**Comment by trevorbaca** [comment]
Fixed.
```
staff = abjad.Staff()
staff.append(abjad.Container("c'4"))
halves = staff[0]._split_by_duration(
    abjad.Duration(1, 20),
    )
abjad.f(staff)
\new Staff
{
    {
        \times 4/5 {
            c'4
            ~
            c'16
        }
    }
}
```
