### ISSUE TITLE
AttributeError: module 'abjad' has no attribute 'lilypondnames'

### ISSUE THREAD

**Issue by PProen** [Abjad/abjad#1102]
Hello, I just installed Abjad today, and I was trying out the homepage example, when I got this message after trying to show the staff

from abjad import *
duration = Duration(1, 4)
notes = [Note(pitch, duration) for pitch in range(8)]
staff = Staff(notes)

`Traceback (most recent call last):

  File "<ipython-input-6-c6716cb55685>", line 1, in <module>
    show(staff)

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\top\show.py", line 51, in show
    result = abjad.persist(argument).as_pdf(**keywords)

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\system\PersistenceManager.py", line 234, in as_pdf
    **keywords

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\system\PersistenceManager.py", line 81, in as_ly
    format_specification='lilypond',

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\lilypondfile\LilyPondFile.py", line 271, in __format__
    return self._get_lilypond_format()

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\lilypondfile\LilyPondFile.py", line 571, in _get_lilypond_format
    return '\n\n'.join(self._get_format_pieces())

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\lilypondfile\LilyPondFile.py", line 504, in _get_format_pieces
    result.extend(self._get_formatted_blocks())

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\lilypondfile\LilyPondFile.py", line 515, in _get_formatted_blocks
    string = item._get_lilypond_format()

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\lilypondfile\Block.py", line 259, in _get_lilypond_format
    return '\n'.join(self._get_format_pieces())

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\lilypondfile\Block.py", line 196, in _get_format_pieces
    result.extend(self._format_item(item))

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\lilypondfile\Block.py", line 169, in _format_item
    pieces = item._get_format_pieces()

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\core\Context.py", line 222, in _get_format_pieces
    return self._format_component(pieces=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\core\Component.py", line 230, in _format_component
    bundle = LilyPondFormatManager.bundle_format_contributions(self)

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\system\LilyPondFormatManager.py", line 279, in bundle_format_contributions
    component, bundle)

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\system\LilyPondFormatManager.py", line 84, in _populate_context_setting_format_contributions
    for name, value in vars(abjad.setting(component)).items():

  File "C:\ProgramData\Anaconda3\lib\site-packages\abjad\top\setting.py", line 39, in setting
    manager = abjad.lilypondnames.LilyPondSettingNameManager()

AttributeError: module 'abjad' has no attribute 'lilypondnames'`

**Comment by trevorbaca** [comment]
@PProen Python is complaining that Abjad has no `lilypondnames` module. But Abjad *definitely* does have a `lilypondnames` module.

Try installing Abjad and see if that fixes the problem.
