### ISSUE TITLE
Make sure parser parses LilyPond \breathe command correctly

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#1119]
Currently:
```
>>> staff = abjad.Staff(r"c'4 d' e' f' \breathe")                                   
Traceback (most recent call last):
  File "/Users/trevorbaca/.abjad/abjad_tmp.py", line 62, in <module>
    staff = abjad.Staff(r"c'4 d' e' f' \breathe")
  File "/Users/trevorbaca/abjad/abjad/core/Staff.py", line 99, in __init__
    tag=tag,
  File "/Users/trevorbaca/abjad/abjad/core/Context.py", line 89, in __init__
    tag=tag,
  File "/Users/trevorbaca/abjad/abjad/core/Container.py", line 202, in __init__
    self._initialize_components(components)
  File "/Users/trevorbaca/abjad/abjad/core/Container.py", line 686, in _initialize_components
    parsed = self._parse_string(components)
  File "/Users/trevorbaca/abjad/abjad/core/Container.py", line 757, in _parse_string
    parsed = parse(user_input)
  File "/Users/trevorbaca/abjad/abjad/top/parse.py", line 39, in parse
    return _lilypond_parsers_by_language[language](string)
  File "/Users/trevorbaca/abjad/abjad/parser/LilyPondParser.py", line 385, in __call__
    input_string, lexer=self._lexer
  File "/Users/trevorbaca/abjad/abjad/parser/_parse.py", line 160, in _parse
    p.callable(pslice)
  File "/Users/trevorbaca/abjad/abjad/parser/LilyPondSyntacticalDefinition.py", line 2740, in p_sequential_music__braced_music_list
    p[0] = self.client._construct_sequential_music(p[1])
  File "/Users/trevorbaca/abjad/abjad/parser/LilyPondParser.py", line 485, in _construct_sequential_music
    ) and x.name in (r"\break", r"\breathe", r"\pageBreak"):
AttributeError: 'LilyPondLiteral' object has no attribute 'name'
```

**Comment by trevorbaca** [comment]
Fixed in development branch.

<img width="252" alt="breathe-parser" src="https://user-images.githubusercontent.com/5804733/63066861-356d1500-beda-11e9-887e-b166c5a854e8.png">
