### ISSUE TITLE
Fix parallel abjad.mutate().split() error

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#115]
_From [trevorb...@gmail.com](https://code.google.com/u/118334091018461915321/) on May 06, 2012 17:55:45_

Both examples here should work:
```
> > > from abjad import *
> > > split = componenttools.split_component_at_prolated_duration_and_fracture_crossing_spanners
> > > string = r'''<< \new Voice { c c c c } \new Voice { s s s s } >>'''
> > > components = p(string)
> > > parts = split(components, (1, 2))
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/josiah/Documents/Projects/abjad/abjad/tools/componenttools/split_component_at_prolated_duration_and_fracture_crossing_spanners.py", line 59, in split_component_at_prolated_duration_and_fracture_crossing_spanners
> > >     spanners = 'fractured', tie_after = tie_after)
> > >   File "/home/josiah/Documents/Projects/abjad/abjad/tools/componenttools/_split_component_at_duration.py", line 121, in _split_component_at_duration
> > >     i = duration_crossing_container.index(prev)
> > >   File "/home/josiah/Documents/Projects/abjad/abjad/tools/containertools/Container/Container.py", line 460, in index
> > >     raise ValueError('component {!r} not in Abjad container {!r}.'.format(component, self))
> > > ValueError: component Voice{2} not in Abjad container Voice{4}.
> > > 
> > > components = p(string)
> > > parts = split(components, (3, 8))
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/josiah/Documents/Projects/abjad/abjad/tools/componenttools/split_component_at_prolated_duration_and_fracture_crossing_spanners.py", line 59, in split_component_at_prolated_duration_and_fracture_crossing_spanners
> > >     spanners = 'fractured', tie_after = tie_after)
> > >   File "/home/josiah/Documents/Projects/abjad/abjad/tools/componenttools/_split_component_at_duration.py", line 120, in _split_component_at_duration
> > >     assert isinstance(duration_crossing_container, containertools.Container)
> > > AssertionError
```
_Original issue: http://code.google.com/p/abjad/issues/detail?id=114_

**Comment by trevorbaca** [comment]
Still valid in May 2017:
```
Traceback (most recent call last):
  File "/Users/trevorbaca/.abjad/abjad_tmp.py", line 10, in <module>
    parts = mutate(container).split([Duration(1, 2)], cyclic=False)
  File "/Users/trevorbaca/abjad/abjad/tools/agenttools/MutationAgent.py", line 2662, in split
    use_messiaen_style_ties=use_messiaen_style_ties,
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Container.py", line 1085, in _split_by_duration
    i = duration_crossing_container.index(previous)
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Container.py", line 1247, in index
    raise ValueError(message)
ValueError: component Voice('s4 s4') not in Abjad container Voice('c4 c4 c4 c4').
```

**Comment by trevorbaca** [comment]
Current output:
```
>>> string = r'''<< \new Voice { c c c c } \new Voice { s s s s } >>'''  
>>> container = abjad.Container(string)  
>>> parts = abjad.mutate(container).split([(1, 2)], cyclic=False)                 

Traceback (most recent call last):
  File "/Users/trevorbaca/.abjad/abjad_tmp.py", line 9, in <module>
    parts = abjad.mutate(container).split([(1, 2)], cyclic=False)                 
  File "/Users/trevorbaca/abjad/abjad/tools/agenttools/MutationAgent.py", line 2628, in split
    use_messiaen_style_ties=use_messiaen_style_ties,
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Container.py", line 1136, in _split_by_duration
    i = container.index(previous)
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Container.py", line 1299, in index
    raise ValueError(message)
ValueError: component Voice('s4 s4') not in Abjad container Voice('c4 c4 c4 c4').
```

**Comment by trevorbaca** [comment]
Simplification:
```
>>> voice_1 = abjad.Voice("a'4 as' b' bs'")
>>> voice_2 = abjad.Voice("c'4 cs' d' ds'")
>>> container = abjad.Container([voice_1, voice_2], is_simultaneous=True)
>>> container._split_by_duration((1, 2))

Traceback (most recent call last):
  File "/Users/trevorbaca/.abjad/abjad_tmp.py", line 15, in <module>
    use_messiaen_style_ties=False,
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Container.py", line 1136, in _split_by_duration
    i = container.index(previous)
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Container.py", line 1299, in index
    raise ValueError(message)
ValueError: component Voice("d'4 ds'4") not in Abjad container Voice("a'4 as'4 b'4 bs'4").
```

**Comment by trevorbaca** [comment]
Turns out that `split()` was never defined for any parallel container.

Method now raises `NotImplementedError` to make this clear.

Extension for parallel containers still pending.

**Comment by trevorbaca** [comment]
Done in 2.21:
```
>>> voice_1 = abjad.Voice("e''4 ( es'' f'' fs'' )", name='Voice 1')                 
>>> voice_2 = abjad.Voice(r"c'4 \p \< cs' d' ds' \f", name='Voice 2')               
>>> container = abjad.Container([voice_1, voice_2], is_simultaneous=True)           
>>> staff = abjad.Staff([container])                                                
>>> abjad.mutate(container).split([abjad.Duration(1, 2)])                           

>>> f(staff)                                                                        
\new Staff {
    <<
        \context Voice = "Voice 1" {
            e''4 (
            es''4
        }
        \context Voice = "Voice 2" {
            c'4 \p \<
            cs'4
        }
    >>
    <<
        \context Voice = "Voice 1" {
            f''4
            fs''4 )
        }
        \context Voice = "Voice 2" {
            d'4
            ds'4 \f
        }
    >>
}

>>> abjad.inspect(staff).is_well_formed()
True
```
