### ISSUE TITLE
Install instruction additions

### ISSUE THREAD

**Issue by 80aff123-9163-4f3e-a93d-4a2f35af9be1** [Abjad/abjad#1209]
Hi @trevorbaca,

I'm replying here instead as I was having issues posting onto google groups.

I've seen it recommended not to install anything with sudo pip for security and system state reasons. 

Using sudo pip on debian/ubuntu distros can mess up the system python that those distros use. [See here](https://stackoverflow.com/questions/21055859/what-are-the-risks-of-running-sudo-pip). 

Running sudo pip is also not safe on fedora. [See here](https://fedoraproject.org/wiki/Changes/Making_sudo_pip_safe).

I haven't checked any other linux distributions.

I therefore installed virtualenv and virtualenvwrapper without sudo by using --user.

There is a way to install virtualenv and virtualenvwrapper on debian/ubuntu with ```apt``` by running the following:

```sh
sudo apt install python3-virtualenv
sudo apt install python3-virtualenvwrapper
```

I haven't tested this with abjad.

What are your thoughts on this? 

I was following the version of the [abjad docs that is here](https://abjad.github.io/).

I was able to get up and running on Ubuntu 20.04.1 like so:

```python
pip3 install --user virtualenvwrapper 
pip3 install --user virtualenv
```

The following command from the docs did not work: 
```sh
source `which virtualenvwrapper.sh`
```

so I added the following to my `~/.bashrc` (this also allowed me to run pip instead of pip3 in the virtualenv):

```python
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_VIRTUALENV=/home/abjad/.local/bin/virtualenv
source ~/.local/bin/virtualenvwrapper.sh
```
I then ran the following:

```python
source ~/.bashrc
mkvirtualenv abjad
pip install abjad
```

# I was also able to get abjad up and running in a simple venv (without having to install virtualenv or virtualenvwrapper) on Ubuntu 20.04 by doing the following:

```python
sudo apt intall python3-venv
mkdir abjad_test
python3 -m venv abjad_test && source abjad_test/bin/activate
pip install abjad
```
Here is what pip list shows in my venv:

```sh
(abjad_test) abjad@vultr:~$ pip list
Package                       Version  
----------------------------- ---------
Abjad                         3.1      
alabaster                     0.7.12  
appdirs                       1.4.4    
attrs                         19.3.0  
Babel                         2.8.0    
black                         19.10b0  
certifi                       2020.6.20
chardet                       3.0.4    
click                         7.1.2    
docutils                      0.16    
idna                          2.10    
imagesize                     1.2.0    
Jinja2                        2.11.2  
MarkupSafe                    1.1.1    
packaging                     20.4    
pathspec                      0.8.0    
pip                           20.0.2  
pkg-resources                 0.0.0    
ply                           3.11    
Pygments                      2.6.1    
pyparsing                     2.4.7    
pytz                          2020.1  
regex                         2020.7.14
requests                      2.24.0  
roman                         3.3      
setuptools                    44.0.0  
six                           1.15.0  
snowballstemmer               2.0.0    
Sphinx                        3.2.0    
sphinx-rtd-theme              0.5.0    
sphinxcontrib-applehelp       1.0.2    
sphinxcontrib-devhelp         1.0.2    
sphinxcontrib-htmlhelp        1.0.3    
sphinxcontrib-jsmath          1.0.1    
sphinxcontrib-qthelp          1.0.3    
sphinxcontrib-serializinghtml 1.1.4    
toml                          0.10.1  
typed-ast                     1.4.1    
Unidecode                     1.1.1    
uqbar                         0.4.6    
urllib3                       1.25.10
```
I'm running python 3.8.2 in the venv.

```sh
(abjad_test) abjad@vultr:~$ which python
/home/abjad/abjad_test/bin/python
(abjad_test) abjad@vultr:~$ which python3
/home/abjad/abjad_test/bin/python3
```
Here's the output of running pip install abjad in the venv (see the few errors below):

```
(abjad_test) abjad@vultr:~$ pip -V
pip 20.0.2 from /home/abjad/abjad_test/lib/python3.8/site-packages/pip (python 3.8)
(abjad_test) abjad@vultr:~$ pip install abjad
Collecting abjad
  Downloading Abjad-3.1.tar.gz (654 kB)
     |████████████████████████████████| 654 kB 23.6 MB/s
Collecting ply
  Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 12.7 MB/s
Collecting roman
  Downloading roman-3.3-py2.py3-none-any.whl (3.9 kB)
Collecting uqbar<0.5.0,>=0.4.4
  Downloading uqbar-0.4.6.tar.gz (56 kB)
     |████████████████████████████████| 56 kB 9.8 MB/s
Collecting Sphinx>=3.0.0
  Downloading Sphinx-3.2.0-py3-none-any.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 30.2 MB/s
Collecting Unidecode>=1.0.0
  Downloading Unidecode-1.1.1-py2.py3-none-any.whl (238 kB)
     |████████████████████████████████| 238 kB 25.8 MB/s
Collecting black>=19.3b0
  Downloading black-19.10b0-py36-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 13.7 MB/s
Collecting sphinx-rtd-theme>=0.4.0
  Downloading sphinx_rtd_theme-0.5.0-py2.py3-none-any.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 25.0 MB/s
Collecting sphinxcontrib-serializinghtml
  Downloading sphinxcontrib_serializinghtml-1.1.4-py2.py3-none-any.whl (89 kB)
     |████████████████████████████████| 89 kB 15.5 MB/s
Collecting sphinxcontrib-qthelp
  Downloading sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 10.2 MB/s
Collecting Jinja2>=2.3
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 36.0 MB/s
Collecting Pygments>=2.0
  Downloading Pygments-2.6.1-py3-none-any.whl (914 kB)
     |████████████████████████████████| 914 kB 32.4 MB/s
Collecting snowballstemmer>=1.1
  Downloading snowballstemmer-2.0.0-py2.py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 12.0 MB/s
Collecting requests>=2.5.0
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 965 kB/s
Collecting alabaster<0.8,>=0.7
  Downloading alabaster-0.7.12-py2.py3-none-any.whl (14 kB)
Collecting imagesize
  Downloading imagesize-1.2.0-py2.py3-none-any.whl (4.8 kB)
Collecting docutils>=0.12
  Downloading docutils-0.16-py2.py3-none-any.whl (548 kB)
     |████████████████████████████████| 548 kB 36.2 MB/s
Collecting packaging
  Downloading packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting sphinxcontrib-jsmath
  Downloading sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting babel>=1.3
  Downloading Babel-2.8.0-py2.py3-none-any.whl (8.6 MB)
     |████████████████████████████████| 8.6 MB 22.5 MB/s
Collecting sphinxcontrib-htmlhelp
  Downloading sphinxcontrib_htmlhelp-1.0.3-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 10.3 MB/s
Requirement already satisfied: setuptools in ./abjad_test/lib/python3.8/site-packages (from Sphinx>=3.0.0->uqbar<0.5.0,>=0.4.4->abjad) (44.0.0)
Collecting sphinxcontrib-applehelp
  Downloading sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 38.0 MB/s
Collecting sphinxcontrib-devhelp
  Downloading sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
     |████████████████████████████████| 84 kB 4.3 MB/s
Collecting pathspec<1,>=0.6
  Downloading pathspec-0.8.0-py2.py3-none-any.whl (28 kB)
Collecting typed-ast>=1.4.0
  Downloading typed_ast-1.4.1-cp38-cp38-manylinux1_x86_64.whl (768 kB)
     |████████████████████████████████| 768 kB 24.5 MB/s
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting attrs>=18.1.0
  Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting click>=6.5
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 2.8 MB/s
Collecting regex
  Downloading regex-2020.7.14-cp38-cp38-manylinux2010_x86_64.whl (672 kB)
     |████████████████████████████████| 672 kB 37.0 MB/s
Collecting toml>=0.9.4
  Downloading toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 39.7 MB/s
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 30.1 MB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 37.0 MB/s
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 13.2 MB/s
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 11.4 MB/s
Collecting pytz>=2015.7
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 48.0 MB/s
Building wheels for collected packages: abjad, uqbar
  Building wheel for abjad (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/abjad/abjad_test/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e8w1k9rw/abjad/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e8w1k9rw/abjad/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0jrb_neb
       cwd: /tmp/pip-install-e8w1k9rw/abjad/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
 
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for abjad
  Running setup.py clean for abjad
  Building wheel for uqbar (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/abjad/abjad_test/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e8w1k9rw/uqbar/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e8w1k9rw/uqbar/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vsui39tl
       cwd: /tmp/pip-install-e8w1k9rw/uqbar/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
 
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for uqbar
  Running setup.py clean for uqbar
Failed to build abjad uqbar
Installing collected packages: ply, roman, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, MarkupSafe, Jinja2, Pygments, snowballstemmer, urllib3, chardet, certifi, idna, requests, alabaster, imagesize, docutils, six, pyparsing, packaging, sphinxcontrib-jsmath, pytz, babel, sphinxcontrib-htmlhelp, sphinxcontrib-applehelp, sphinxcontrib-devhelp, Sphinx, Unidecode, pathspec, typed-ast, appdirs, attrs, click, regex, toml, black, sphinx-rtd-theme, uqbar, abjad
    Running setup.py install for uqbar ... done
    Running setup.py install for abjad ... done
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 Pygments-2.6.1 Sphinx-3.2.0 Unidecode-1.1.1 abjad-3.1 alabaster-0.7.12 appdirs-1.4.4 attrs-19.3.0 babel-2.8.0 black-19.10b0 certifi-2020.6.20 chardet-3.0.4 click-7.1.2 docutils-0.16 idna-2.10 imagesize-1.2.0 packaging-20.4 pathspec-0.8.0 ply-3.11 pyparsing-2.4.7 pytz-2020.1 regex-2020.7.14 requests-2.24.0 roman-3.3 six-1.15.0 snowballstemmer-2.0.0 sphinx-rtd-theme-0.5.0 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-1.0.3 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.4 toml-0.10.1 typed-ast-1.4.1 uqbar-0.4.6 urllib3-1.25.10
```
Simple tests of the abjad api like the ones I tried before worked depsite the above errors.

**Comment by trevorbaca** [comment]
Thanks for documenting these here, @ccao001 .

I certainly agree with "no sudo" for installing (Abjad, and Python packages in general). I hadn't noticed that our install instructions still point to sudo; that will be removed.

I'll keep your comments open here for the next time I have a chance to update the install docs.

**Comment by jgarte** [comment]
@trevorbaca 

Great! I'm glad I could help.

If you need me to test anything out on any linux distribution regarding abjad just let me know.

I'd also be happy to submit a pull request to update the installation procedure for ubuntu/debian if needed.

**Comment by ccao001** [comment]
@trevorbaca, I'm glad I could help!

I'd be happy to submit a pull request for review to update the docs. Just let me know if needed. 

I'm also happy to test anything abjad related on any linux distribution.

**Comment by trevorbaca** [comment]
@ccao001 are you able to build the Abjad docs? It's something of a task the first time you do it. But if you're able to, then perhaps you could just document the complete set of install steps that you used, top to bottom? That way we'd having something testable that we could conceivably link to on the doc site.

If you can't yet build the Abjad docs, you could still format your install steps in markdown, proof them in an online markdown visualizer, and send over.

**Comment by ccao001** [comment]
Hi @trevorbaca ,

I'm getting the error below when trying to build the abjad docs on debian.

I followed the docs to install the development version of abjad.

Is there anything that I might be missing from my install process? Let me know what information you need from me that would be helpful in debugging this. 

## after running ajv doctest

```
(abjad) ruben@ruben:~/abjad$ ajv doctest
Traceback (most recent call last):
  File "/home/ruben/.virtualenvs/abjad/bin/ajv", line 33, in <module>
    sys.exit(load_entry_point('Abjad', 'console_scripts', 'ajv')())
  File "/home/ruben/abjad/abjad/cli.py", line 604, in run_ajv
    AbjDevScript()()
  File "/home/ruben/.virtualenvs/abjad/lib/python3.7/site-packages/uqbar/cli/CLI.py", line 48, in __init__
    self._setup_argument_parser(parser)
  File "/home/ruben/.virtualenvs/abjad/lib/python3.7/site-packages/uqbar/cli/CLIAggregator.py", line 133, in _setup_argument_parser
    alias_map = self.cli_aliases
  File "/home/ruben/.virtualenvs/abjad/lib/python3.7/site-packages/uqbar/cli/CLIAggregator.py", line 164, in cli_aliases
    for cli_class in self.cli_classes:
  File "/home/ruben/abjad/abjad/cli.py", line 80, in cli_classes
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ruben/.virtualenvs/abjad/lib/python3.7/site-packages/abjadext/rmakers/__init__.py", line 6, in <module>
    from .commands import (
  File "/home/ruben/.virtualenvs/abjad/lib/python3.7/site-packages/abjadext/rmakers/commands.py", line 362, in <module>
    class WrittenDurationCommand(Command):
  File "/home/ruben/.virtualenvs/abjad/lib/python3.7/site-packages/abjadext/rmakers/commands.py", line 377, in WrittenDurationCommand
    selector: abjad.Expression = abjad.Expression().select().leaf(0),
  File "/home/ruben/abjad/abjad/expression.py", line 491, in __getattr__
    raise AttributeError(f"{class_name} object has no attribute {name!r}.")
AttributeError: Expression object has no attribute 'select'.
```
## after running ajv api -M

```
(abjad) ruben@ruben:~/abjad$ ajv api -M
Traceback (most recent call last):
  File "/home/ruben/.virtualenvs/abjad/bin/ajv", line 33, in <module>
    sys.exit(load_entry_point('Abjad', 'console_scripts', 'ajv')())
  File "/home/ruben/abjad/abjad/cli.py", line 604, in run_ajv
    AbjDevScript()()
  File "/home/ruben/.virtualenvs/abjad/lib/python3.7/site-packages/uqbar/cli/CLI.py", line 48, in __init__
    self._setup_argument_parser(parser)
  File "/home/ruben/.virtualenvs/abjad/lib/python3.7/site-packages/uqbar/cli/CLIAggregator.py", line 133, in _setup_argument_parser
    alias_map = self.cli_aliases
  File "/home/ruben/.virtualenvs/abjad/lib/python3.7/site-packages/uqbar/cli/CLIAggregator.py", line 164, in cli_aliases
    for cli_class in self.cli_classes:
  File "/home/ruben/abjad/abjad/cli.py", line 80, in cli_classes
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ruben/.virtualenvs/abjad/lib/python3.7/site-packages/abjadext/rmakers/__init__.py", line 6, in <module>
    from .commands import (
  File "/home/ruben/.virtualenvs/abjad/lib/python3.7/site-packages/abjadext/rmakers/commands.py", line 362, in <module>
    class WrittenDurationCommand(Command):
  File "/home/ruben/.virtualenvs/abjad/lib/python3.7/site-packages/abjadext/rmakers/commands.py", line 377, in WrittenDurationCommand
    selector: abjad.Expression = abjad.Expression().select().leaf(0),
  File "/home/ruben/abjad/abjad/expression.py", line 491, in __getattr__
    raise AttributeError(f"{class_name} object has no attribute {name!r}.")
AttributeError: Expression object has no attribute 'select'.
```

**Comment by trevorbaca** [comment]
Hi @ccao001 wow, that sounds great. And yes that's almost exactly my workflow.

Importantly -- and to your earlier point -- I never use `sudo` with pip! The fact that the Abjad docs still mention `sudo pip` is ancient (and will be changing when we update the docs for Abjad 3.2, which will show up in a month or two).

So if you leave out the `sudo` for your last step and just go with `pip install -e.[test]` then you're following my workflow exactly.

Good luck with the PR!

**Comment by trevorbaca** [comment]
Hi @ccao001, I don't believe you ever introduced yourself. May I ask who you are, and with whom I've had the pleasure of working on this issue?
