### ISSUE TITLE
Fix abjad.NamedInterval.from_pitch_carriers() case

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#1221]
```
>>> pitch_1 = abjad.NamedPitch("ds'")
>>> pitch_2 = abjad.NamedPitch("ef''")
>>> abjad.NamedInterval.from_pitch_carriers(pitch_1, pitch_2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/trevorbaca/abjad/abjad/pitch/intervals.py", line 886, in from_pitch_carriers
    named_ic_number
KeyError: 9
```

**Comment by trevorbaca** [comment]
Fixed by @nivlekp in 3.2:
```
pitch_1 = abjad.NamedPitch("ds'")
pitch_2 = abjad.NamedPitch("ef''")
abjad.NamedInterval.from_pitch_carriers(pitch_1, pitch_2)
NamedInterval('+d9')
```

**Comment by trevorbaca** [comment]
Reopening because I've found a class of cases that need a similar fix:
```
pitch_1 = abjad.NamedPitch("c'")
pitch_2 = abjad.NamedPitch("dfff''")
abjad.NamedInterval.from_pitch_carriers(pitch_1, pitch_2)
Traceback (most recent call last):
  File "/Users/trevorbaca/.abjad/tmp.py", line 7, in <module>
    abjad.NamedInterval.from_pitch_carriers(pitch_1, pitch_2)
  File "/Users/trevorbaca/abjad/abjad/pitch/intervals.py", line 892, in from_pitch_carriers
    for key, value in constants._diatonic_number_and_quality_to_semitones[
KeyError: 9
```
I think I see the problem; will fix and open a PR.

**Comment by trevorbaca** [comment]
This is the test output we will want to see in `abjad.NamedInterval.from_pitch_carriers()` to know we've fixed the problem:
```
>>> abjad.NamedInterval.from_pitch_carriers("c'", "d''")
NamedInterval('+M9')

>>> abjad.NamedInterval.from_pitch_carriers("c'", "df''")
NamedInterval('+m9')

>>> abjad.NamedInterval.from_pitch_carriers("c'", "dff''")
NamedInterval('+d9')

>>> abjad.NamedInterval.from_pitch_carriers("c'", "dfff''")
NamedInterval('+dd9')

>>> abjad.NamedInterval.from_pitch_carriers("c'", "dffff''")
NamedInterval('+ddd9')
```
The output intervals read, respectively, as major ninth; minor ninth; diminished ninth; doubly-diminished ninth; triply-diminished ninth. (All ascending.)
