### ISSUE TITLE
Add WellformednessManager.check_overlapping_ties() method

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#577]
Making this structure by hand is currently allowed:
```
>>> staff = Staff("c'4 c'4 c'4")
>>> attach(Tie(), staff[:2])
>>> attach(Tie(), staff[1:3])
```
We might refer to this sort of configuration as comprising enchained ties.

But making enchained ties is bad because it confuses our model of logical ties:
```
>>> inspect_(staff[1]).get_logical_tie()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/trevorbaca/Documents/abjad/abjad/tools/agenttools/InspectionAgent.py", line 501, in get_logical_tie
    return self._client._get_logical_tie()
  File "/Users/trevorbaca/Documents/abjad/abjad/tools/scoretools/Leaf.py", line 348, in _get_logical_tie
    raise Exception(message)
Exception: parentage of Note("c'4") contains 2 tie spanners.
```
The correct way to make the structure shown above is with a single tie:
```
>>> staff = Staff("c'4 c'4 c'4")
>>> attach(Tie(), staff[:])
>>> inspect_(staff[1]).get_logical_tie()
LogicalTie(Note("c'4"), Note("c'4"), Note("c'4"))
```
The issue created here asks that ``WellformednessManager`` extended to include a ``check_overlapping_ties()`` method.

This will prevent rhythm-makers from producing output with enchained ties.

**Comment by trevorbaca** [comment]
Done in PR.
