### ISSUE TITLE
Compiling within sublime text

### ISSUE THREAD

**Issue by jguessfo** [Abjad/abjad#657]
I am able to compile Lilypond files with no problem in the command line, but when I use Sublime Text I get an error.  Anyway I can fix this so that I can use the editor?

The code is a simple
from abjad import *
note = Note("c'4")
show(note)

The error is:
Traceback (most recent call last):
  File "/Users/Jesse/Desktop/python3_Stuff/abjadtester.py", line 4, in <module>
    show(note)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/abjad/tools/topleveltools/show.py", line 30, in show
    result = topleveltools.persist(expr).as_pdf(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/abjad/tools/agenttools/PersistenceAgent.py", line 226, in as_pdf
    **kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/abjad/tools/agenttools/PersistenceAgent.py", line 78, in as_ly
    illustration = illustrate_function(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/abjad/tools/scoretools/Component.py", line 117, in __illustrate__
    lilypond_file = lilypondfiletools.make_basic_lilypond_file(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/abjad/tools/lilypondfiletools/make_basic_lilypond_file.py", line 87, in make_basic_lilypond_file
    use_relative_includes=use_relative_includes,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/abjad/tools/lilypondfiletools/LilyPondFile.py", line 142, in __init__
    token = lilypondfiletools.LilyPondVersionToken()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/abjad/tools/lilypondfiletools/LilyPondVersionToken.py", line 29, in __init__
    version_string = abjad_configuration.get_lilypond_version_string()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/abjad/tools/systemtools/AbjadConfiguration.py", line 228, in get_lilypond_version_string
    lilypond_version_string = proc.stdout.readline().decode(encoding)
TypeError: decode() argument 1 must be str, not None
[Finished in 1.0s with exit code 1]

**Comment by josiah-wolf-oberholtzer** [comment]
What happens when you run the following in SublimeText?

```
import locale
print(locale.getdefaultlocale())
```

**Comment by jguessfo** [comment]
I get (None, None)

**Comment by josiah-wolf-oberholtzer** [comment]
I have a PR up at #658 addressing this. I don't have SublimeText, so I can't verify that it works correctly. Would you mind testing this? You'll need to uninstall Abjad, clone the repository, checkout the branch and install Abjad in "edit" mode.

```
pip uninstall abjad
git clone https://github.com/Abjad/abjad.git
cd abjad
pip install -e .
git checkout issue657/sublime-text-locale
```

**Comment by jguessfo** [comment]
Worked!!

**Comment by josiah-wolf-oberholtzer** [comment]
@jguessfo Thanks! Merging...
