### ISSUE TITLE
Make NumberedPitchClass format correctly in unspecified strings

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#730]
Example (that should not error):

```
>>> pc = NumberedPitchClass(1)
>>> print 'foo: {}'.format(pc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/trevorbaca/Documents/abjad/abjad/tools/pitchtools/PitchClass.py", line 187, in __format__
    return self._lilypond_format
AttributeError: 'NumberedPitchClass' object has no attribute '_lilypond_format'
```

Of course asking for `'foo {!s}'` with the forced-string `!s` indicator works fine.

But all system objects should work fine when passed into "bald" formatting strings.

This also suggests a new parametric test (to check for the safety of such bald formatting against all system objects).

**Comment by trevorbaca** [comment]
Done during 2.20.

But will leave issue open until parametric test is added.

**Comment by trevorbaca** [comment]
Closing in favor of separate issue for parametric tests.
