### ISSUE TITLE
Fix MetronomeMarkSpanner last-leaf bug

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#917]
To reproduce:
```
segment_2 = abjad.Voice("g'4 a' b' r")
spanner = abjad.MetronomeMarkSpanner()
abjad.attach(spanner, segment_2[:])
mark = abjad.MetronomeMark((1, 4), 90)
spanner.attach(mark, spanner[-1])
abjad.f(segment_2)
```
Output:
```
Traceback (most recent call last):
  File "/Users/trevorbaca/.abjad/abjad_tmp.py", line 15, in <module>
    abjad.f(segment_2)
  File "/Users/trevorbaca/abjad/abjad/tools/topleveltools/f.py", line 62, in f
    string = format(argument, 'lilypond')
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Component.py", line 96, in __format__
    return self._get_lilypond_format()
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Context.py", line 224, in _get_lilypond_format
    return self._format_component(strict=strict)
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Component.py", line 239, in _format_component
    result.extend(self._format_contents_slot(bundle, strict=strict))
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Container.py", line 571, in _format_contents_slot
    self._format_content_pieces(strict=strict)
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Container.py", line 559, in _format_content_pieces
    format_specification=format_specification
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Component.py", line 96, in __format__
    return self._get_lilypond_format()
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Component.py", line 481, in _get_lilypond_format
    return self._format_component(strict=strict)
  File "/Users/trevorbaca/abjad/abjad/tools/scoretools/Component.py", line 234, in _format_component
    bundle = abjad.LilyPondFormatManager.bundle_format_contributions(self)
  File "/Users/trevorbaca/abjad/abjad/tools/systemtools/LilyPondFormatManager.py", line 317, in bundle_format_contributions
    manager._populate_spanner_format_contributions(component, bundle)
  File "/Users/trevorbaca/abjad/abjad/tools/systemtools/LilyPondFormatManager.py", line 271, in _populate_spanner_format_contributions
    spanner_bundle = spanner._get_lilypond_format_bundle(component)
  File "/Users/trevorbaca/abjad/abjad/tools/spannertools/MetronomeMarkSpanner.py", line 2480, in _get_lilypond_format_bundle
    previous_metronome_mark,
  File "/Users/trevorbaca/abjad/abjad/tools/spannertools/MetronomeMarkSpanner.py", line 2707, in _start_tempo_trend_spanner_with_implicit_start
    markup = current_tempo_trend._get_markup()
AttributeError: 'NoneType' object has no attribute '_get_markup'
```

**Comment by trevorbaca** [comment]
Fixed in development branch.
