### ISSUE TITLE
can't graph staff containing measures

### ISSUE THREAD

**Issue by jefftrevino** [Abjad/abjad#972]
I'm able to graph a staff that contains leaves directly but no measures; however, when I try to graph a staff that contains leaves in `Measure()` or `Tuplet()` instances, `Measure()` can't find `graphtools`:

```
staff = abjad.Staff("c'4. c'4. c'4. c'4. c'4. c'4. c'4. c'4.")

abjad.mutate(staff[:]).split([abjad.Duration(4,4)], cyclic=True)

duration = abjad.Duration(4,4)

for shard in abjad.mutate(staff[:]).split([duration] , cyclic=True):
   abjad.mutate(shard).wrap(abjad.Measure())

abjad.graph(staff)
```
yields, for `Measure()`:

```
File ..."/abjad/tools/topleveltools/graph.py", line 314, in graph
    graphviz_graph = argument.__graph__(**keywords)
  File "/Users/simjeff/Virtualenvs/three/lib/python3.6/site-packages/abjad/tools/scoretools/Container.py", line 354, in __graph__
    component_node, node_order = recurse(self, leaf_cluster)
  File "/Users/simjeff/Virtualenvs/three/lib/python3.6/site-packages/abjad/tools/scoretools/Container.py", line 324, in recurse
    child, this_leaf_cluster)
  File "/Users/simjeff/Virtualenvs/three/lib/python3.6/site-packages/abjad/tools/scoretools/Container.py", line 306, in recurse
    component_node = component._as_graphviz_node()
  File "/Users/simjeff/Virtualenvs/three/lib/python3.6/site-packages/abjad/tools/scoretools/Measure.py", line 235, in _as_graphviz_node
    graphtools.GraphvizTableRow([
NameError: name 'graphtools' is not defined
```
and for `Tuplet()`:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-17-78a7f2671ca8> in <module>()
      1 staff = abjad.Staff(r"c'4 \times 2/3 { d'8 e'8 f'8 } g'4")
----> 2 abjad.graph(staff)

~/Virtualenvs/three/lib/python3.6/site-packages/abjad/tools/ipythontools/Graph.py in __call__(self, argument, layout, graph_attributes, node_attributes, edge_attributes, **keywords)
     30         else:
     31             assert hasattr(argument, '__graph__')
---> 32             graphviz_graph = argument.__graph__(**keywords)
     33             if graph_attributes:
     34                 graphviz_graph.attributes.update(graph_attributes)

~/Virtualenvs/three/lib/python3.6/site-packages/abjad/tools/scoretools/Container.py in __graph__(self, spanner, **keywords)
    352             )
    353         leaf_cluster = graphtools.GraphvizSubgraph(name='leaves')
--> 354         component_node, node_order = recurse(self, leaf_cluster)
    355         if len(leaf_cluster) == 1:
    356             graph.append(leaf_cluster[0])

~/Virtualenvs/three/lib/python3.6/site-packages/abjad/tools/scoretools/Container.py in recurse(component, leaf_cluster)
    322                         all_are_leaves = False
    323                     child_node, child_node_order = recurse(
--> 324                         child, this_leaf_cluster)
    325                     pending_node_order.extend(child_node_order)
    326                     edge = graphtools.GraphvizEdge()

~/Virtualenvs/three/lib/python3.6/site-packages/abjad/tools/scoretools/Container.py in recurse(component, leaf_cluster)
    304         '''
    305         def recurse(component, leaf_cluster):
--> 306             component_node = component._as_graphviz_node()
    307             node_mapping[component] = component_node
    308             node_order = [component_node.name]

~/Virtualenvs/three/lib/python3.6/site-packages/abjad/tools/scoretools/Tuplet.py in _as_graphviz_node(self)
    142         node = scoretools.Component._as_graphviz_node(self)
    143         node[0].extend([
--> 144             graphtools.GraphvizTableRow([
    145                 graphtools.GraphvizTableCell(
    146                     label=type(self).__name__,
```

**Comment by trevorbaca** [comment]
Closing: `abjad.Measure` removed in Abjad 3.1.
